services:
  backend:
    image: {{username}}/oakhouse-scraper:{{version}}
    restart: always
    environment:
      - QUARKUS_MAILER_FROM={{QUARKUS_MAILER_FROM}}
      - QUARKUS_MAILER_HOST={{QUARKUS_MAILER_HOST}}
      - QUARKUS_MAILER_PORT={{QUARKUS_MAILER_PORT}}
      - QUARKUS_MAILER_USERNAME={{QUARKUS_MAILER_USERNAME}}
      - QUARKUS_MAILER_PASSWORD={{QUARKUS_MAILER_PASSWORD}}
      - SCRAPER_EMAIL_RECIPIENT={{SCRAPER_EMAIL_RECIPIENT}}
      - SCRAPER_TARGET_URLS={{SCRAPER_TARGET_URLS}}
      - QUARKUS_MAILER_TLS=FALSE
      - QUARKUS_MAILER_START_TLS=REQUIRED
      - TZ=UTC

